version: "3.8"

networks:
  stamford:

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: stamfordcenter
    volumes:
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
